TAREA GRUPAL 1 /Grupo 5
1. Use f-string para concatenar textos o valores numéricos. De dos ejemplos 

In [29]:
x1 = "Este es nuestro primer trabajo grupal"
x2 = "Jupyter notebooks"
print (f'{x1} del ciclo 2022-1 en {x2}')

Este es nuestro primer trabajo grupal del ciclo 2022-1 en Jupyter notebooks


In [32]:
y1 = 101
y2 = 10
y3= y1+y2
print(f'{y1} + {y2} es {y3}')

101 + 10 es 111


DICCIONAIRO Y LISTAS
2. Crear una lista de tres distritos de Lima y dos distritos del callao. Extraer el primer y último elemento usando el indexing

In [43]:
lista = ["Los Olivos", "Ancón", "Ventanilla", "Santiago de Surco", "Mi Perú"]
print(lista)

['Los Olivos', 'Ancón', 'Ventanilla', 'Santiago de Surco', 'Mi Perú']


2.1 Extrar el primero

In [41]:
lista[0]

'Los Olivos'

2.2 extraer el último

In [44]:
lista[-1]

'Mi Perú'

3. Crear un diccionario con los 5 distritos del ejercicio a. Incluir información de población proyectada e incidencia de pobreza (limite superior).Use la información del Mapa de Pobreza 2018

In [2]:
diccionario ={"Los Olivos":{"población":351983, "pobreza":9.5}, "Ancón":{"población":82677,"pobreza":25.5, 
"Ventanilla":{"población":369618, "pobreza":29.4}, "Santiago de Surco":{"población":408086, "pobreza":1.6}, 
"Mi Perú":{"población":52348,"pobreza":31.0 }}}
print(diccionario)

{'Los Olivos': {'población': 351983, 'pobreza': 9.5}, 'Ancón': {'población': 82677, 'pobreza': 25.5, 'Ventanilla': {'población': 369618, 'pobreza': 29.4}, 'Santiago de Surco': {'población': 408086, 'pobreza': 1.6}, 'Mi Perú': {'población': 52348, 'pobreza': 31.0}}}


4. Muestre la información de pobreza y población de 3 distritos

In [3]:
diccionario["Los Olivos"]["población"] , diccionario["Los Olivos"]["pobreza"]

(351983, 9.5)

In [4]:
diccionario["Ancón"]["población"] , diccionario["Ancón"]["pobreza"]

(82677, 25.5)

In [6]:
diccionario["Mi Perú"]["población"] , diccionario["Mi Perú"]["pobreza"]

KeyError: 'Mi Perú'

MATRICES 
5. crear matrices y dar dos ejemplos de concatenación, union vertical y horizontal

In [10]:
import numpy as np


In [24]:
matriz_1 = np.arange(5,11).reshape(3,2)
print(matriz_1)

[[ 5  6]
 [ 7  8]
 [ 9 10]]


In [26]:
matriz_2 = np.arange(1,7).reshape(3,2)
print(matriz_2)

[[1 2]
 [3 4]
 [5 6]]


5.1 Concatenación horizontal.

In [27]:
matriz_3 =np.concatenate((matriz_1, matriz_2), 1)
print(matriz_3)

[[ 5  6  1  2]
 [ 7  8  3  4]
 [ 9 10  5  6]]


5.2 Concatenación vertical 

In [28]:
matriz_4 =np.concatenate((matriz_1, matriz_2), 0)
print(matriz_4)

[[ 5  6]
 [ 7  8]
 [ 9 10]
 [ 1  2]
 [ 3  4]
 [ 5  6]]


6. Crea una matriz de dimensión 4x8, seleccionar las 2 últimas columnas y las 3 primers filas 

In [58]:
matriz_4x8 = np.arange(1,33).reshape(4,8)
print(matriz_4x8)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


6.1 Seleccionamos las 2 últimás columnas 

In [62]:
matriz_4x8[:,6:8]

array([[ 7,  8],
       [15, 16],
       [23, 24],
       [31, 32]])

6.2 Seleccionamos las 3 primeras filas

In [66]:
matriz_4x8[0:3,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

7. Obtener el estimador de la varianza del termino de perturbación

In [3]:
import numpy as np
import random 

random.seed(5)

x1 = np.random.rand(5) 
x2 = np.random.rand(5) 
x3 = np.random.rand(5) 
x4 = np.random.rand(5)
e = np.random.normal(0,1,5)

Y = 1 + 1.4*x1 + 1.2*x2 + 1.3*x3 + e
Y

array([2.77736735, 2.78935435, 3.09580353, 3.85220596, 2.80201448])

In [4]:
X = np.column_stack((x1,x2,x3))  #matriz X
print (X)

[[0.47447144 0.37330671 0.86560054]
 [0.0790435  0.27396311 0.63338098]
 [0.98310531 0.34459887 0.77910145]
 [0.97898862 0.83458816 0.86970915]
 [0.37099934 0.8732202  0.21609938]]


FORMULA DEL ESTIMADOR DE LA VARIANZA

\begin{equation}
 \hat{\sigma}^2 = {\frac{\sum(\hat{e})^2}{N-K}} = {\frac{\sum(Y- \hat{Y})^2}{N-K}} = {\frac{\sum({Y-XB})^2}{N-K}}
\end{equation}

In [5]:
B = np.linalg.inv(X.T @ X) @ ((X.T) @ Y )  #betas estimados

B

array([-0.2822084 ,  2.4487603 ,  2.74729197])

In [15]:
U =  Y - X@B
U

array([ 0.10978472, -0.15881615,  0.47727375, -0.17392966,  0.04283958])

In [25]:
S2 = sum(pow(U,2))/(5-4)
S2

0.29715224247337857

8. Matriz de varianza y covarianza de los coeficientes

\begin{equation}
 \Sigma = (\frac{\hat{U}'\hat{U}}{n-k})(X'X)^{-1}
\end{equation}

In [20]:
CV = (U.T @ U / (5-4))*(np.linalg.inv(X.T@X))
CV

array([[ 0.41438113, -0.21936548, -0.10624676],
       [-0.21936548,  0.57715007, -0.69329027],
       [-0.10624676, -0.69329027,  1.60080993]])

9. Matriz generador de residuos

\begin{equation}
 M = I - X(X'X)^{-1}X'
\end{equation}

In [21]:
I = np.eye(5) # Matriz Identidad
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
M = I - X@(np.linalg.inv(X.T@X)@X.T)
M

array([[ 0.52177807,  0.11805452,  0.10776176, -0.21747581, -0.42033382],
       [ 0.11805452,  0.14978622, -0.28026674,  0.03668885, -0.183079  ],
       [ 0.10776176, -0.28026674,  0.77634824, -0.25752647,  0.13095696],
       [-0.21747581,  0.03668885, -0.25752647,  0.1505879 ,  0.11379587],
       [-0.42033382, -0.183079  ,  0.13095696,  0.11379587,  0.40149957]])