### Pregunta 1

In [23]:
library(glue)

In [24]:
year <- 2020
poverty_rate <- "30.1 %"
glue('En {year}, la tasa de pobreza a nivel nacional fue {poverty_rate}.')

En 2020, la tasa de pobreza a nivel nacional fue 30.1 %.

In [25]:
name <- "Juan"
age <- 20
glue('{name} el próximo año tendra {age+1} años.')

Juan el próximo año tendra 21 años.

# Diccionarios y Listas

### Pregunta 2

In [11]:
distritos <- list('Breña','Surco','Chorrillos','Bellavista','La Perla')
cat("Distritos")
print(distritos)
cat("\n","Primer y último distrito")
print(distritos[c(1,length(distritos))])

Distritos[[1]]
[1] "Breña"

[[2]]
[1] "Surco"

[[3]]
[1] "Chorrillos"

[[4]]
[1] "Bellavista"

[[5]]
[1] "La Perla"


 Primer y último distrito[[1]]
[1] "Breña"

[[2]]
[1] "La Perla"



### Pregunta 3

In [13]:
diccionario <- list(Breña = list(Poverty_Rate = "5.4 %", Population = "93.1 mil"),
                    Surco = list(Poverty_Rate = "1.6 %", Population = "408 mil"),
                    Chorrillos = list(Poverty_Rate = "14.3 %", Population = "355.9 mil"),
                    Bellavista = list(Poverty_Rate = "6.3 %", Population = "80.7 mil"),
                    La_Perla = list(Poverty_Rate = "4.7 %", Population = "64.5 mil"))
diccionario

$Breña
$Breña$Poverty_Rate
[1] "5.4 %"

$Breña$Population
[1] "93.1 mil"


$Surco
$Surco$Poverty_Rate
[1] "1.6 %"

$Surco$Population
[1] "408 mil"


$Chorrillos
$Chorrillos$Poverty_Rate
[1] "14.3 %"

$Chorrillos$Population
[1] "355.9 mil"


$Bellavista
$Bellavista$Poverty_Rate
[1] "6.3 %"

$Bellavista$Population
[1] "80.7 mil"


$La_Perla
$La_Perla$Poverty_Rate
[1] "4.7 %"

$La_Perla$Population
[1] "64.5 mil"

### Pregunta 4

In [14]:
print(diccionario$Surco)

$Poverty_Rate
[1] "1.6 %"

$Population
[1] "408 mil"



In [15]:
print(diccionario$Bellavista)

$Poverty_Rate
[1] "6.3 %"

$Population
[1] "80.7 mil"



In [16]:
print(diccionario$La_Perla)

$Poverty_Rate
[1] "4.7 %"

$Population
[1] "64.5 mil"



# Matrices

### Pregunta 5

In [36]:
M <- matrix(1:9,nrow=3,byrow=T)
N <- matrix(10:15,nrow=2)
O <- matrix(6:9,nrow=2)
cat("Matriz M\n")
print(M)
cat("\nMatriz N\n")
print(N)
cat("\nMatriz O\n")
print(O)


Matriz M
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

Matriz N
     [,1] [,2] [,3]
[1,]   10   12   14
[2,]   11   13   15

Matriz O
     [,1] [,2]
[1,]    6    8
[2,]    7    9


In [38]:
P <- rbind(M,N)
P

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   12   14  
[5,] 11   13   15

In [45]:
R <- cbind(O,N)
R

[,1] [,2] [,3] [,4] [,5]
[1,] 6    8    10   12   14  
[2,] 7    9    11   13   15

### Pregunta 6

In [44]:
Q <- matrix(32:1,nrow=4)
cat("Matriz Q\n")
print(Q)
cat("\nSlide\n")
print(Q[1:3,7:8])

Matriz Q
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]   32   28   24   20   16   12    8    4
[2,]   31   27   23   19   15   11    7    3
[3,]   30   26   22   18   14   10    6    2
[4,]   29   25   21   17   13    9    5    1

Slide
     [,1] [,2]
[1,]    8    4
[2,]    7    3
[3,]    6    2


# Operaciones con Matrices

### Pregunta 7:Obtener el estimador de la varianza del termino de perturbación

In [55]:
set.seed(6)

x1 <- runif(6)
x2 <- runif(6)
x3 <- runif(6)
x4 <- runif(6)
u <- rnorm(6)

Y <- 1 + 0.9*x1 + 1.4*x2 + 1.5*x3+ x4 + u
print(Y)

[1] 3.830032 3.686721 3.464760 2.699423 5.231537 3.325284


In [38]:
X <- cbind(matrix(1,6), x1,x2,x3,x4) #MATRIZ x
X

x1        x2        x3         x4       
[1,] 1 0.6062683 0.9579337 0.09523258 0.1472278
[2,] 1 0.9376420 0.7627319 0.29537280 0.7005260
[3,] 1 0.2643521 0.5096485 0.76993170 0.9579925
[4,] 1 0.3800939 0.0644768 0.25589353 0.8286251
[5,] 1 0.8074834 0.6435728 0.51789573 0.1192788
[6,] 1 0.9780757 0.9159089 0.67784993 0.2403410

FORMULA DEL ESTIMADOR DE LA VARIANZA

\begin{equation}
 \hat{\sigma}^2 = {\frac{\sum(\hat{U})^2}{N-K}} = {\frac{\sum(Y- \hat{Y})^2}{N-K}} = {\frac{\sum({Y-XB})^2}{N-K}}
\end{equation}

In [54]:
install.packages("matlib")
library("matlib")

B <- inv(t(X) %*% X) %*% (t(X) %*% Y)  # Matriz Betas Estimados
print(B)

               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes          

ERROR: Error in inv(t(X) %*% X): no se pudo encontrar la función "inv"


In [ ]:
Y_est = X %*% B   # matriz Y estimados
print(Y_est)


In [ ]:
U <- Y - Y_est  # Matriz errores estimados
print(U)

In [ ]:
S2= sum(U^2)/(5-4)  
print (S2)

### Pregunta 8: Matriz de varianza y covarianza de los coeficientes¶

\begin{equation}
 \Sigma = (\frac{\hat{U}'\hat{U}}{n-k})(X'X)^{-1}
\end{equation}

In [ ]:
CV <- (t(U) %*% U / (5-4))*(inv(t(X) %*% X))
print(CV)

### Pregunta 9: Matriz generador de residuos


\begin{equation}
 M = I - X(X'X)^{-1}X'
\end{equation}

In [ ]:
I <- diag(5)
print(I)

In [ ]:
M = I - X %*% (inv(t(X) %*% X)%*% t(X))
print(M)